"$schema" = 'https://raw.githubusercontent.com/yazi-rs/schemas/refs/heads/main/schemas/keymap.json'

[[mgr.prepend_keymap]]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
on = ["g", "r"]
desc = "Go to git root"

[[mgr.prepend_keymap]]
run = 'help'
on = ["g", "?"]
desc = "Show help"

[[mgr.prepend_keymap]]
on = ["<C-f>"]
run = "seek 5"
desc = "Scroll preview down"

[[mgr.prepend_keymap]]
on = ["<C-b>"]
run = "seek -5"
desc = "Scroll preview up"

[[mgr.prepend_keymap]]
on = ["<C-n>"]
run = "arrow 1"
desc = "Scroll preview down"

[[mgr.prepend_keymap]]
on = ["<C-p>"]
run = "arrow -1"
desc = "Scroll preview up"

[[mgr.prepend_keymap]]
on = "H"
run = "plugin duckdb -1"
desc = "Scroll one column to the left"

[[mgr.prepend_keymap]]
on = "L"
run = "plugin duckdb +1"
desc = "Scroll one column to the right"

[[mgr.prepend_keymap]]
on = ["g", "o"]
run = "plugin duckdb -open"
desc = "open with duckdb"

[[mgr.prepend_keymap]]
on = ["g", "u"]
run = "plugin duckdb -ui"
desc = "open with duckdb ui"
