#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config external_bar all:49:0 \
  window_border on \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_zoom_persist off \
  window_placement second_child \
  window_topmost off \
  window_shadow float \
  window_opacity on \
  window_opacity_duration 0.15 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.85 \
  window_border_width 2 \
  window_border_hidpi off \
  window_border_radius 11 \
  window_animation_duration 0 \
  active_window_border_color 0xffe1e3e4 \
  normal_window_border_color 0xff2a2f38 \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  auto_balance off \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  top_padding 10 \
  bottom_padding 10 \
  left_padding 10 \
  right_padding 10 \
  window_gap 8

# Space labels
yabai -m space 1 --label "Start" --display 1
yabai -m space 2 --label "Browser" --display 2
yabai -m space 3 --label "Code" --display 2
yabai -m space 4 --label "Notes" --display 2
yabai -m space 5 --label "Misc" --display 2

# Start
yabai -m rule --add app="Slack" space="Start"
yabai -m rule --add app="Safari" space="Start"

# Browser, disabled to allow little arc on same space
# yabai -m rule --add app="Arc" space="Browser"

# Programming
yabai -m rule --add app="kitty" space="Code"

# Notes
yabai -m rule --add app="Notion" space="Notes"
yabai -m rule --add app="Obsidian" space="Notes"
yabai -m rule --add app="Calendar" space="Notes"
yabai -m rule --add app="Linear" space="Notes"
yabai -m rule --add app="Notes" space="Notes"

# Misc
yabai -m rule --add app="Spotify" space="Misc"
yabai -m rule --add app="Discord" space="Misc"
yabai -m rule --add app="Whatsapp" space="Misc"

yabai -m rule --add app="^(Calculator|Software Update|Dictionary|System Preferences|System Settings|Photo Booth|Archive Utility|App Store|Steam|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^1Password$" manage=off

yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"

yabai -m config layout stack

yabai -m rule --apply
