#!/bin/bash

source "$CONFIG_DIR/colors.sh"

export PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

bar=(
  height=39
  color="$BASE"
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=9
  y_offset=10
  margin=10
  blur_radius=20
  notch_width=200
)

sketchybar --bar "${bar[@]}"

sketchybar --default icon.font="SF Pro:Semibold:15.0" \
  icon.color="$ICON_COLOR" \
  label.font="SF Pro:Semibold:15.0" \
  label.color="$TEXT" \
  background.color="$BASE" \
  background.corner_radius=5 \
  background.height=24 \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=4 \
  label.padding_right=4 \
  icon.padding_left=4 \
  icon.padding_right=4

# -- Left Side Items --
source "$ITEM_DIR"/spaces.sh
source "$ITEM_DIR"/front_app.sh

# -- Right Side Items --
source "$ITEM_DIR"/calendar.sh
source "$ITEM_DIR"/volume.sh
source "$ITEM_DIR"/battery.sh
source "$ITEM_DIR"/ram.sh
source "$ITEM_DIR"/cpu.sh
source "$ITEM_DIR"/media.sh

# Aerospace
# sketchybar --add event aerospace_workspace_change
# for sid in $(aerospace list-workspaces --all); do
#   sketchybar --add item space."$sid" left \
#     --subscribe space."$sid" aerospace_workspace_change \
#     --set space."$sid" \
#     background.color=0x44ffffff \
#     background.corner_radius=5 \
#     background.height=20 \
#     background.drawing=off \
#     label="$sid" \
#     click_script="aerospace workspace $sid" \
#     script="$CONFIG_DIR/plugins/aerospace.sh $sid"
# done

sketchybar --update
