return {
  { "mason-org/mason-lspconfig.nvim" },
  {
    "mason-org/mason.nvim",
    cmd = "Mason",
    keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
    build = ":MasonUpdate",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "biome",
        "black",
        "codelldb",
        "golangci-lint",
        "golangci-lint-langserver",
        "gopls",
        "html-lsp",
        "jq",
        "json-lsp",
        "lua-language-server",
        "markdownlint",
        "marksman",
        "prettier",
        "prettierd",
        "postgres-language-server",
        "sqlfluff",
        "rustywind",
        "shellcheck",
        "shfmt",
        "stylua",
        "svelte-language-server",
        "tailwindcss-language-server",
        "terraform-ls",
        "vtsls",
        "yaml-language-server",
        "zls",
      },
    },
  },
}
