# vim:ft=kitty


#
# THEME STARTS CATPPUCCIN-MOCHA
#
# The basic colors
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5E0DC

# Cursor colors
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# URL underline color when hovering with mouse
url_color               #F5E0DC

# Kitty window border colors
active_border_color     #B4BEFE
inactive_border_color   #6C7086
bell_border_color       #F9E2AF

# OS Window titlebar colors
#macos_titlebar_color    #1E1E2E

# Tab bar colors
active_tab_foreground   #11111B
active_tab_background   #CBA6F7
inactive_tab_foreground #CDD6F4
inactive_tab_background #181825
tab_bar_background      #11111B

# Colors for marks (marked text in the terminal)
mark1_foreground #1E1E2E
mark1_background #B4BEFE
mark2_foreground #1E1E2E
mark2_background #CBA6F7
mark3_foreground #1E1E2E
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

color5  #cba6f7
color13 #cba6f7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8
#
# THEME ENDS
#

# Tab bar
tab_bar_min_tabs 1
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{':' if num_windows > 1 and layout_name == 'stack' else ''}{num_windows if num_windows > 1 and layout_name == 'stack' else ''}
# tab_title_template          {'' if session_name == '' else session_name + ':'}{title}{':' if num_windows > 1 and layout_name == 'stack' else ''}{num_windows if num_windows > 1 and layout_name == 'stack' else ''}
tab_title_max_length 15

# Various styles
window_margin_width 0
window_padding_width 5
hide_window_decorations titlebar-only
background_blur 10
background_opacity 1
dynamic_background_opacity yes
cursor_trail 1

# Fonts
font_family      JetBrainsMono Nerd Font Mono
font_size 15.0

# MacOS specifics
macos_option_as_alt right
macos_show_window_title_in none

editor /opt/homebrew/bin/nvim

allow_remote_control yes
listen_on unix:/tmp/kitty
shell_integration enabled

enabled_layouts grid,fat,stack
auto_reload_config -1
update_check_interval 0
disable_ligatures always
enable_audio_bell no

# Keybinds
map cmd+enter new_window
map cmd+shift+enter new_window_with_cwd

map cmd+shift+t new_tab_with_cwd

map kitty_mod+t detach_tab ask
map kitty_mod+d detach_window ask

map kitty_mod+h previous_tab
map kitty_mod+l next_tab
map kitty_mod+ö next_layout

map ctrl+shift+1 goto_tab 1
map ctrl+shift+2 goto_tab 2
map ctrl+shift+3 goto_tab 3
map ctrl+shift+4 goto_tab 4
map ctrl+shift+5 goto_tab 5

# Sessions
startup_session $HOME/startup.kitty-session
map f7>s save_as_session --use-foreground-process

# map f7>g goto_session
# map f7>g send_text normal,application cli-toolbox kitty-session\r
map f7>g launch --type=overlay --cwd=current sh -lc 'exec cli-toolbox kitty select-session'

map f7>x close_session

map cmd+k clear_terminal scroll active

# Use neovim to view scrollback and last command output
scrollback_pager_history_size 3
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set readonly nolist' +'$' -
map kitty_mod+g show_scrollback
map kitty_mod+o show_last_command_output
