[settings]
install_before = "7d"

[tools]
java = "latest"
lua = "5.1"
node = "24"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:knip" = "latest"
"npm:neovim" = "latest"
python = "latest"
terraform = "latest"
uv = "latest"
